# TODO: See if we can automate wallet version bumps

name: Talisman CI

on:
  push:
    branches: ["dev"]
  pull_request:
    types: [opened, synchronize]

concurrency:
  # only run 1 job per branch/pr/etc at a time
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # This job will build and test the talisman wallet
  build:
    name: "Build and test the wallet"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # also get the previous commit
      - name: Update & enable corepack
        run: npm install -g corepack@latest && corepack enable
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm preconstruct:dev && pnpm test
      - name: Extract short SHA + package version
        id: vars
        run: |
          sha_short=$(git rev-parse --short HEAD)
          echo "sha_short=$sha_short" >> $GITHUB_OUTPUT
          npm_package_version=$(cat apps/extension/package.json | jq -r .version)
          echo "npm_package_version=$npm_package_version" >> $GITHUB_OUTPUT
      - name: Extract translatable strings
        run: pnpm chore:update-translations
      - name: Upload translatable strings
        uses: simplelocalize/github-action-cli@v1
        with:
          api-key: ${{ secrets.SIMPLE_LOCALIZE_API_KEY }}
          command: "upload"
          cli-version: "2.2.0"
          args: "--uploadPath ./apps/extension/.i18next-parser/locales/{lang}/{ns}.json --apiKey ${{ secrets.SIMPLE_LOCALIZE_API_KEY }}"
      - name: Build
        run: pnpm build:extension:ci
        env:
          COMMIT_SHA_SHORT: ${{ steps.vars.outputs.sha_short }}
          POSTHOG_AUTH_TOKEN: ${{ secrets.POSTHOG_AUTH_TOKEN }}
          E2E_TESTS_MNEMONIC: ${{ secrets.E2E_TESTS_MNEMONIC }}
          # SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          # SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./apps/extension/dist/chrome/talisman_extension_ci_${{ steps.vars.outputs.sha_short }}_chrome.zip
          retention-days: 5

  # This job will use the files from the build job to run Playwright tests
  playwright:
    name: "E2E test the wallet with Playwright"
    needs: build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      E2E_TESTS_MNEMONIC: ${{ secrets.E2E_TESTS_MNEMONIC }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Update & enable corepack
        run: npm install -g corepack@latest && corepack enable
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build papi descriptors
        run: pnpm papi
      - name: Download build artifact # download wallet that was built in the build job
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build-artifact
      - name: Unzip build artifact to the playwright extension path
        run: |
          mkdir -p ./apps/extension/dist/chrome
          unzip ./build-artifact/*.zip -d ./apps/extension/dist/chrome
      - name: Cache playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-
      - name: Install playwright browser - chromium with system dependencies
        run: pnpm exec playwright install --with-deps chromium
      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb
      - name: Run playwright tests with xvfb
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" \
          pnpm test:e2e
      - name: "Upload playwright report"
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
